name: 01 - Bulding Blocks
on: workflow_dispatch
jobs:
  echo-hello: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
  echo-goodbye: 
    runs-on: ubuntu-latest
    steps:
      - name: success step
        run: |
          echo "I will success"
          exit 0
      - name: Say Goodbye 
        run: echo "Goodbye!"