name: 06 Contexts 
on: 
  push: 
  workflow_dispatch:
    inputs:
      debug: 
        description: test input variable 
        type: boolean 
        default: false 
  
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
env: 
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
        env: 
          MY_JOB_VAR: 'job'
          MY_OVERWRITTEN_VAR: 'job'
      - name: Retrieve Variable 
        run: echo "${{ vars.MY_VAR }}"
      - name: Print Env Variables 
        run: |
          "workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
        env: 
          MY_VERWRITEEN_VAR: 'step' 
      - name: Print Env Variables
        run: |
          "workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
      