name: 12 - Working with Outputs
on: 
  workflow_dispatch:
    inputs:
      buils-status:
        type: choice
        options:
          - success
          - failure
        default: success
jobs:
  build: 
    runs-on: ubuntu-latest 
    outputs:
      output1: ${{ steps.build.outputs.output1 }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT "
      - name: Build
        id: build
        run: |
          #echo "status=success" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
          echo "mistake=true" > "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
          

  deploy: 
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Print outputs
        run: echo "${{needs.build.outputs.output1}}"