name: 12 - Working with Outputs
on: 
  workflow_dispatch:
    inputs:
      buils-status:
        type: choice
        options:
          - success
          - failure
        default: success
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo " ${{ environment }} >> $GITHUB_OUTPUT "
  deploy: 
    runs-on: ubuntu-latest
    needs: build 
    if: ${{ needs.build.status }}
    steps:
      - name: deploy
        run: echo "deploying..."