name: 13 - Using Caching 
on: 
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step
      node-version: 
        type: choice 
        default: '20.x'
        options:
          - 18.x
          - 20.x
          - 21.x 
jobs:
  build:
    runs-on: ubuntu-latest 
    defaults:
      run: 
        working-directory: 13-Caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node 
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ inputs.node-version }}
      
      - name: Download dependencies 
        id: cache 
        if: ${{ inputs.use-cache == 'true' }}
        uses: actions/cache@v3 
        with: 
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
          path: '13-caching/react-app/node_modules'

      # name: install 
      #  run: npm install

      - name: Install dependencies 
        if: ${{ steps.cache.outputs.cache-hit == 'true'}}
        run: npm ci 

      - name: Testing 
        run: npm run test 

      - name: bulid
        run: npm run build

      - name: deploying to non-prod 
        run: echo " Deploying to non-prod "


      